"""autogenerated by genmsg_py from Info.msg. Do not edit."""
import roslib.message
import struct


class Info(roslib.message.Message):
  _md5sum = "ccad5ec9e04587167a37cc31cf635143"
  _type = "nao_landmark_detection/Info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Fields
float32 alpha
float32 beta
float32 sizeX
float32 sizeY
float32 heading
uint8 id

"""
  __slots__ = ['alpha','beta','sizeX','sizeY','heading','id']
  _slot_types = ['float32','float32','float32','float32','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       alpha,beta,sizeX,sizeY,heading,id
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.alpha is None:
        self.alpha = 0.
      if self.beta is None:
        self.beta = 0.
      if self.sizeX is None:
        self.sizeX = 0.
      if self.sizeY is None:
        self.sizeY = 0.
      if self.heading is None:
        self.heading = 0.
      if self.id is None:
        self.id = 0
    else:
      self.alpha = 0.
      self.beta = 0.
      self.sizeX = 0.
      self.sizeY = 0.
      self.heading = 0.
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_5fB.pack(_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id,) = _struct_5fB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_5fB.pack(_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id,) = _struct_5fB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_5fB = struct.Struct("<5fB")
