"""autogenerated by genmsg_py from LandmarkDetection.msg. Do not edit."""
import roslib.message
import struct

import nao_landmark_detection.msg
import std_msgs.msg

class LandmarkDetection(roslib.message.Message):
  _md5sum = "ea761ceb52fdb9033947d758d5d365d2"
  _type = "nao_landmark_detection/LandmarkDetection"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Fields
std_msgs/Header header

nao_landmark_detection/Info[] info

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: nao_landmark_detection/Info
# Fields
float32 alpha
float32 beta
float32 sizeX
float32 sizeY
float32 heading
uint8 id

"""
  __slots__ = ['header','info']
  _slot_types = ['std_msgs/Header','nao_landmark_detection/Info[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       header,info
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(LandmarkDetection, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.info is None:
        self.info = []
    else:
      self.header = std_msgs.msg.Header()
      self.info = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.info)
      buff.write(_struct_I.pack(length))
      for val1 in self.info:
        _x = val1
        buff.write(_struct_5fB.pack(_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.info = []
      for i in range(0, length):
        val1 = nao_landmark_detection.msg.Info()
        _x = val1
        start = end
        end += 21
        (_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id,) = _struct_5fB.unpack(str[start:end])
        self.info.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.info)
      buff.write(_struct_I.pack(length))
      for val1 in self.info:
        _x = val1
        buff.write(_struct_5fB.pack(_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.info = []
      for i in range(0, length):
        val1 = nao_landmark_detection.msg.Info()
        _x = val1
        start = end
        end += 21
        (_x.alpha, _x.beta, _x.sizeX, _x.sizeY, _x.heading, _x.id,) = _struct_5fB.unpack(str[start:end])
        self.info.append(val1)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3I = struct.Struct("<3I")
_struct_5fB = struct.Struct("<5fB")
