- {height: 30, width: 30, x: 137, y: 3}
- {height: 30, width: 30, x: 110, y: 35}
- {height: 30, width: 30, x: 70, y: 79}
- {height: 30, width: 30, x: 22, y: 171}
- {height: 30, width: 30, x: 140, y: 166}
- {height: 30, width: 30, x: 248, y: 169}
- {height: 30, width: 30, x: 368, y: 171}
- {height: 30, width: 30, x: 486, y: 162}
- {height: 30, width: 30, x: 465, y: 87}
- {height: 30, width: 30, x: 443, y: 47}
- {height: 30, width: 30, x: 420, y: 13}
