- {height: 30, width: 30, x: 136, y: 8}
- {height: 30, width: 30, x: 100, y: 45}
- {height: 30, width: 30, x: 66, y: 105}
- {height: 30, width: 30, x: 30, y: 187}
- {height: 30, width: 30, x: 151, y: 194}
- {height: 30, width: 30, x: 271, y: 188}
- {height: 30, width: 30, x: 363, y: 194}
- {height: 30, width: 30, x: 508, y: 202}
- {height: 30, width: 30, x: 480, y: 122}
- {height: 30, width: 30, x: 456, y: 66}
- {height: 30, width: 30, x: 440, y: 29}
